/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peachbound1;
import java.util.*;

/**
 *
 * @author Cameron
 */
public class Combat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Combat.class.getName());
    private boolean turn = true;
    @SuppressWarnings("NonPublicExported")
    public ArrayList<Monster> targets;
    private Monster currTarget;
    private int currTargetNum;
    public Player player;
    
    // Enum for enemy move types
    private enum EnemyMove {
        BLOCK,
        ATTACK,
        SPECIAL_ATTACK
    }
    
    // Queue to store enemy moves
    private Queue<EnemyMove> enemyMoveQueue;
    
    /**
     * Creates new form Combat
     */
    public Combat() {
        initComponents();
        player = new Player();
        targets = new ArrayList<>();
        currTargetNum = 0;
        
        // Add all the enemies
        Monster enemy1 = new Brute("Big Guy");
        Monster enemy2 = new FireMonster("Draco");
        Monster enemy3 = new IceMonster("Mr Freeze");
        targets.add(enemy1);
        targets.add(enemy2);
        targets.add(enemy3);
        
        currTarget = targets.get(currTargetNum);
        
        
        enemyMoveQueue = new LinkedList<>();
        
        UpdateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        skill1Name = new javax.swing.JLabel();
        skill1Use = new javax.swing.JButton();
        skill1Desc = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        skill2Name = new javax.swing.JLabel();
        skill2Use = new javax.swing.JButton();
        skill2Desc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        skill3Name = new javax.swing.JLabel();
        skill3Use = new javax.swing.JButton();
        skill3Desc = new javax.swing.JLabel();
        weaponUse = new javax.swing.JButton();
        smallHealUse = new javax.swing.JButton();
        medHealUse = new javax.swing.JButton();
        blockUse = new javax.swing.JButton();
        largeHealUse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        playerHealthVal = new javax.swing.JLabel();
        dfLvl = new javax.swing.JLabel();
        atkLvl = new javax.swing.JLabel();
        weaknessText = new javax.swing.JLabel();
        strengthText = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        enHealthVal = new javax.swing.JLabel();
        enDfLvl = new javax.swing.JLabel();
        enAtkLvl = new javax.swing.JLabel();
        enWeaknessText = new javax.swing.JLabel();
        enStrengthText = new javax.swing.JLabel();
        enName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        skill1Name.setForeground(new java.awt.Color(255, 255, 255));
        skill1Name.setText("Skill1 Name");

        skill1Use.setText("Use");
        skill1Use.addActionListener(this::skill1UseActionPerformed);

        skill1Desc.setForeground(new java.awt.Color(255, 255, 255));
        skill1Desc.setText("Description:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(skill1Use)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(skill1Name)
                                .addGap(37, 37, 37))))
                    .addComponent(skill1Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(skill1Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(skill1Desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(skill1Use)
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        skill2Name.setForeground(new java.awt.Color(255, 255, 255));
        skill2Name.setText("Skill2 Name");

        skill2Use.setText("Use");
        skill2Use.addActionListener(this::skill2UseActionPerformed);

        skill2Desc.setForeground(new java.awt.Color(255, 255, 255));
        skill2Desc.setText("Description:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(skill2Use)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(skill2Name)
                                .addGap(37, 37, 37))))
                    .addComponent(skill2Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(skill2Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(skill2Desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(skill2Use)
                .addGap(19, 19, 19))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        skill3Name.setForeground(new java.awt.Color(255, 255, 255));
        skill3Name.setText("Skill3 Name");

        skill3Use.setText("Use");
        skill3Use.addActionListener(this::skill3UseActionPerformed);

        skill3Desc.setForeground(new java.awt.Color(255, 255, 255));
        skill3Desc.setText("Description:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(skill3Use)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(skill3Name)
                                .addGap(37, 37, 37))))
                    .addComponent(skill3Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(skill3Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(skill3Desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(skill3Use)
                .addGap(19, 19, 19))
        );

        weaponUse.setBackground(new java.awt.Color(51, 51, 51));
        weaponUse.setForeground(new java.awt.Color(255, 255, 255));
        weaponUse.setText("Use Weapon");
        weaponUse.addActionListener(this::weaponUseActionPerformed);

        smallHealUse.setBackground(new java.awt.Color(51, 51, 51));
        smallHealUse.setForeground(new java.awt.Color(255, 255, 255));
        smallHealUse.setText("Small Heal");
        smallHealUse.addActionListener(this::smallHealUseActionPerformed);

        medHealUse.setBackground(new java.awt.Color(51, 51, 51));
        medHealUse.setForeground(new java.awt.Color(255, 255, 255));
        medHealUse.setText("Medium Heal");
        medHealUse.addActionListener(this::medHealUseActionPerformed);

        blockUse.setBackground(new java.awt.Color(51, 51, 51));
        blockUse.setForeground(new java.awt.Color(255, 255, 255));
        blockUse.setText("Block");
        blockUse.addActionListener(this::blockUseActionPerformed);

        largeHealUse.setBackground(new java.awt.Color(51, 51, 51));
        largeHealUse.setForeground(new java.awt.Color(255, 255, 255));
        largeHealUse.setText("Large Heal");
        largeHealUse.addActionListener(this::largeHealUseActionPerformed);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        playerHealthVal.setForeground(new java.awt.Color(255, 255, 255));
        playerHealthVal.setText("Health: 000");

        dfLvl.setForeground(new java.awt.Color(0, 153, 153));
        dfLvl.setText("Defense Lvl: 00");

        atkLvl.setForeground(new java.awt.Color(255, 153, 51));
        atkLvl.setText("Offense Lvl: 00");

        weaknessText.setForeground(new java.awt.Color(255, 255, 255));
        weaknessText.setText("Weakness: Enum");

        strengthText.setForeground(new java.awt.Color(255, 255, 255));
        strengthText.setText("Strength: Enum");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerHealthVal)
                    .addComponent(dfLvl)
                    .addComponent(atkLvl)
                    .addComponent(weaknessText)
                    .addComponent(strengthText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerHealthVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dfLvl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atkLvl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(weaknessText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strengthText)
                .addGap(14, 14, 14))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        enHealthVal.setForeground(new java.awt.Color(255, 255, 255));
        enHealthVal.setText("Health: 000");

        enDfLvl.setForeground(new java.awt.Color(0, 153, 153));
        enDfLvl.setText("Defense Lvl: 00");

        enAtkLvl.setForeground(new java.awt.Color(255, 153, 51));
        enAtkLvl.setText("Offense Lvl: 00");

        enWeaknessText.setForeground(new java.awt.Color(255, 255, 255));
        enWeaknessText.setText("Weakness: Enum");

        enStrengthText.setForeground(new java.awt.Color(255, 255, 255));
        enStrengthText.setText("Strength: Enum");

        enName.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        enName.setForeground(new java.awt.Color(255, 255, 255));
        enName.setText("VS Enemy Name");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enHealthVal)
                    .addComponent(enDfLvl)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(enAtkLvl)
                        .addGap(222, 222, 222)
                        .addComponent(enName))
                    .addComponent(enWeaknessText)
                    .addComponent(enStrengthText))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enHealthVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enDfLvl)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enAtkLvl))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(enName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(enWeaknessText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enStrengthText)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weaponUse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smallHealUse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medHealUse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blockUse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(largeHealUse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(weaponUse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockUse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(smallHealUse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medHealUse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(largeHealUse))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public void UpdateUI(){
        // Set the text to the screen
        playerHealthVal.setText("Health: " + String.valueOf(player.getHealth()));
        dfLvl.setText("Deffence Level: " + String.valueOf(player.getDefense_lvl()));
        atkLvl.setText("Offense Level: " + String.valueOf(player.getOffense_lvl()));
        weaknessText.setText("Weakness: " + String.valueOf(player.getWeakness()));
        strengthText.setText("Strength: " + String.valueOf(player.getStrength()));
        
        enHealthVal.setText("Health: " + String.valueOf(currTarget.getHealth()));
        enDfLvl.setText("Deffence Level: " + String.valueOf(currTarget.getDefence()));
        enAtkLvl.setText("Offense Level: " + String.valueOf(currTarget.getOffense()));
        enWeaknessText.setText("Weakness: " + String.valueOf(currTarget.getWeakness()));
        enStrengthText.setText("Strength: " + String.valueOf(currTarget.getStrength()));
        enName.setText("VS " + currTarget.getName());
        
        skill1Name.setText(String.valueOf(player.getInventory().getCurrAbilities().get(0).getName()));
        skill1Desc.setText(String.valueOf(player.getInventory().getCurrAbilities().get(0).getDesc()));
        skill2Name.setText(String.valueOf(player.getInventory().getCurrAbilities().get(1).getName()));
        skill2Desc.setText(String.valueOf(player.getInventory().getCurrAbilities().get(1).getDesc()));
        skill3Name.setText(String.valueOf(player.getInventory().getCurrAbilities().get(2).getName()));
        skill3Desc.setText(String.valueOf(player.getInventory().getCurrAbilities().get(2).getDesc()));
    }
    
    // Put main code for combat here such as
    public boolean getTurn(){
        return turn;
    }
    public void setTurn(boolean t){
        turn = t;
    }
    
    public void Lose(){
        EndScreen winWindow = new EndScreen();
        winWindow.endText = "You have been slain...\nYou LOSE";
        winWindow.setVisible(true);
        this.setVisible(false);
    }
    
    public void SwitchTarget(){
        if(currTargetNum == targets.size()){
            EndScreen winWindow = new EndScreen();
            winWindow.endText = "Congrats! You fought off all the enemies...\nYou WIN";
            winWindow.setVisible(true);
            this.setVisible(false);
        }
        else{
            currTargetNum++;
            currTarget = targets.get(currTargetNum);
        }
    }
    
    // Generates 5 moves for the enemy and stores them in a queue
    private void generateEnemyMoves() {
        // if queue already has 5 moves, stop recursion
        if (enemyMoveQueue.size() >= 5) {
            return;
        }
        
        // randomly select a move type
        Random random = new Random();
        int moveChoice = random.nextInt(3); // 0 = BLOCK, 1 = ATTACK, 2 = SPECIAL_ATTACK
        
        EnemyMove move;
        switch (moveChoice) {
            case 0:
                move = EnemyMove.BLOCK;
                break;
            case 1:
                move = EnemyMove.ATTACK;
                break;
            case 2:
                move = EnemyMove.SPECIAL_ATTACK;
                break;
            default:
                move = EnemyMove.ATTACK; // fallback
                break;
        }
        
        // add to the queue
        enemyMoveQueue.offer(move);
        
        // recursively call to fill queue until it has 5 elements
        generateEnemyMoves();
    }
    
    // executes one enemy move from the queue
    // calls generateEnemyMoves() if queue is empty
    // executes enemy moves
    public void executeEnemyTurn() {
        // Check if player is already defeated
        if (player.getHealth() <= 0) {
            Lose();
            return;
        }
        
        // Check if current monster is defeated
        if (currTarget != null && currTarget.getHealth() <= 0) {
            SwitchTarget();
            // check for multiple targets
            if (currTarget != null && currTargetNum < targets.size() && currTarget.getHealth() > 0) {
                enemyMoveQueue.clear();
                generateEnemyMoves();
                executeEnemyTurn();
            }
            return;
        }
        
        
        if (currTarget == null) {
            return;
        }
        
        // if queue is empty, generate new moves (5 turns worth)
        if (enemyMoveQueue.isEmpty()) {
            generateEnemyMoves();
        }
        
        // execute the next move from the queue
        EnemyMove move = enemyMoveQueue.poll();
        
        if (move != null) {
            switch (move) {
                case BLOCK:
                    // check if player's offense > monster's defense
                    currTarget.block(currTarget.getDefence(), player, player.getCurWeapon());
                    break;
                    
                case ATTACK:
                    
                    currTarget.attack(currTarget.getDmg(), currTarget.getDmgType(), 
                                     currTarget.getStrength(), player);
                    
                    if (player.getHealth() <= 0) {
                        Lose();
                        return;
                    }
                    break;
                    
                case SPECIAL_ATTACK:
                    
                    currTarget.specialAttack(currTarget.getDmg(), currTarget.getDmgType(), 
                                            currTarget.getStrength(), currTarget.getStamina(), player);
                
                    if (player.getHealth() <= 0) {
                        Lose();
                        return;
                    }
                    break;
            }
            
            
            UpdateUI();
        }
        // Only execute one move per call - no recursion
    }
    
    // Every button simply calls other methods defined in the Player class
    private void smallHealUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallHealUseActionPerformed
        player.useConsumable(player.getInventory().getSmallConsumable());
        
        executeEnemyTurn();
    }//GEN-LAST:event_smallHealUseActionPerformed

    private void medHealUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medHealUseActionPerformed
        player.useConsumable(player.getInventory().getMediumConsumable());
   
        executeEnemyTurn();
    }//GEN-LAST:event_medHealUseActionPerformed

    private void blockUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockUseActionPerformed
        player.block(currTarget);
        
        executeEnemyTurn();
    }//GEN-LAST:event_blockUseActionPerformed

    private void largeHealUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeHealUseActionPerformed
        player.useConsumable(player.getInventory().getBigConsumable());
        
        executeEnemyTurn();
    }//GEN-LAST:event_largeHealUseActionPerformed

    private void weaponUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponUseActionPerformed
        player.attack(currTarget);
        
        executeEnemyTurn();
    }//GEN-LAST:event_weaponUseActionPerformed

    private void skill1UseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skill1UseActionPerformed
        player.useSkill(player.getInventory().getCurrAbilities().get(0), currTarget);
       
        executeEnemyTurn();
    }//GEN-LAST:event_skill1UseActionPerformed

    private void skill2UseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skill2UseActionPerformed
        player.useSkill(player.getInventory().getCurrAbilities().get(1), currTarget);
        
        executeEnemyTurn();
    }//GEN-LAST:event_skill2UseActionPerformed

    private void skill3UseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skill3UseActionPerformed
        player.useSkill(player.getInventory().getCurrAbilities().get(2), currTarget);
        
        executeEnemyTurn();
    }//GEN-LAST:event_skill3UseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Combat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atkLvl;
    private javax.swing.JButton blockUse;
    private javax.swing.JLabel dfLvl;
    private javax.swing.JLabel enAtkLvl;
    private javax.swing.JLabel enDfLvl;
    private javax.swing.JLabel enHealthVal;
    private javax.swing.JLabel enName;
    private javax.swing.JLabel enStrengthText;
    private javax.swing.JLabel enWeaknessText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton largeHealUse;
    private javax.swing.JButton medHealUse;
    private javax.swing.JLabel playerHealthVal;
    private javax.swing.JLabel skill1Desc;
    private javax.swing.JLabel skill1Name;
    private javax.swing.JButton skill1Use;
    private javax.swing.JLabel skill2Desc;
    private javax.swing.JLabel skill2Name;
    private javax.swing.JButton skill2Use;
    private javax.swing.JLabel skill3Desc;
    private javax.swing.JLabel skill3Name;
    private javax.swing.JButton skill3Use;
    private javax.swing.JButton smallHealUse;
    private javax.swing.JLabel strengthText;
    private javax.swing.JLabel weaknessText;
    private javax.swing.JButton weaponUse;
    // End of variables declaration//GEN-END:variables
}
